
# NOTE THIS FOLDER DOES NOT GET INCLUDED IN THE INSTALLED VERSION OF THIS PACKAGE
# IT IS IN THE SOURCE CODE COPY OF THE PACKAGE BUT WHEN YOU BUILD/INSTALL, THIS FOLDER DOES NOT GET BUNDLED WITH THAT.


