# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_ejscreenRESTbroker_1pts_1miles.R or similar files

#' @name testoutput_ejscreenRESTbroker_1pts_1miles
#' @docType data
#' @title test data, output from this function
#' @details Just for convenience, installed with the package,
#'  the equivalent of results of 
#'   `ejscreenRESTbroker(lon = testpoints_5$lon[1], lat = testpoints_5$lat[1], radius = 1)`
#' @seealso [testpoints_5] [testpoints_50] [testpoints_500]
#'   
#'   [testoutput_ejscreenit_5] [testoutput_ejscreenit_50] [testoutput_ejscreenit_500]
'testoutput_ejscreenRESTbroker_1pts_1miles'
