# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_epa_programs_defined.R or similar files

#' @name epa_programs_defined
#' @docType data
#' @title Full names and definitions for acronyms of EPA programs in Facility Registry Services (FRS)
#' @seealso [epa_programs]
'epa_programs_defined'
