# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_names_pct_as_fraction_blockgroupstats.R or similar files

#' @name names_pct_as_fraction_blockgroupstats
#' @docType data
#' @title which indicators are percentages stored as 0-1 not 0-100, in blockgroupstats
#' @keywords internal
'names_pct_as_fraction_blockgroupstats'
