# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_ejamit_10pts_1miles.R or similar files

#' @name testoutput_ejamit_10pts_1miles
#' @docType data
#' @title test output of ejamit()
#' @details This is the output of ejamit(testpoints_10, radius = 1, include_ejindexes = TRUE)
#' @seealso [doaggregate()] [ejamit()] [testoutput_doaggregate_10pts_1miles] and [testpoints_10]
'testoutput_ejamit_10pts_1miles'
