# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_naics_counts.R or similar files

#' @name naics_counts
#' @docType data
#' @title naics_counts (DATA) data.frame with regulated facility counts for each industry code
#' @description data.frame with regulated facility counts for each NAICS code, with and without subcodes, and labels that include the site counts
#' @details This has all available NAICS codes, the count of sites for each of them in the frs data, both on their own and including all subcodes. Used by EJAM shiny app for dropdown menu.
'naics_counts'
