# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_x_anyother.R or similar files

#' @name x_anyother
#' @docType data
#' @title for internal use
#' @keywords internal
'x_anyother'
