# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_statestats.R or similar files

#' @name statestats
#' @docType data
#' @title statestats (DATA) data.frame of 100 percentiles and means for each US State and PR and DC.
#' @description data.frame of 100 percentiles and means 
#'   for each US State and PR and DC
#'   for all the block groups in that zone (e.g., block groups in [blockgroupstats])
#'   for a set of indicators such as percent low income.
#'   Each column is one indicator (or specifies the percentile).
#'   
#'   This should be similar to the lookup tables in the gdb on the FTP site of EJScreen,
#'   except it also has data for the demographic race/ethnicity subgroups.
#'   See also [usastats] for more details.
'statestats'
