# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_avg.in.us.R or similar files

#' @name avg.in.us
#' @docType data
#' @title avg.in.us (DATA) national averages of key indicators, for convenience
#' @description also available via [usastats] and created by /data-raw/datacreate_avg.in.us
'avg.in.us'
