# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_names_d_subgroups_nh_pctile.R or similar files

#' @name names_d_subgroups_nh_pctile
#' @docType data
#' @title a list of variable names for internal use in EJAM
#' @details To see other groups of variables: unique(map_headernames$varlist)
#' @keywords internal
#' @seealso  [varinfo()]  [map_headernames]  [names_d] [names_e]
'names_d_subgroups_nh_pctile'
