# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_ejscreenapi_1pts_1miles.R or similar files

#' @name testoutput_ejscreenapi_1pts_1miles
#' @docType data
#' @title test data, output from this function
#' @details Just for convenience, installed with the package,
#'  the equivalent of results of 
#'  
#'  ejscreenapi(lon = testpoints_5$lon[1], lat = testpoints_5$lat[1],
#'     
#'      radius = 1, unit = 'miles', wkid = 4326,
#'     
#'      report_every_n = 25, # report_every_n = 1000,
#'     
#'      save_when_report = FALSE, format_report_or_json =  'pjson', on_server_so_dont_save_files = FALSE, 
#'      ipurl = 'ejscreen.epa.gov',
#'     
#'      updateProgress = NULL, drop_redundant_indicators = FALSE)
#' @seealso [testpoints_5] [testpoints_50] [testpoints_500]
#'   
#'   [testoutput_ejscreenit_5] [testoutput_ejscreenit_50] [testoutput_ejscreenit_500]
'testoutput_ejscreenapi_1pts_1miles'
