# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_lat_alias.R or similar files

#' @name lat_alias
#' @docType data
#' @title lat_alias, lon_alias (DATA) Synonyms for lat and lon
#' @aliases lon_alias
#' @description lists of synonyms for 'latitude' and 'longitude' used when guessing which column is what in user-provided tables of coordinates
'lat_alias'
