# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_bg_cenpop2020.R or similar files

#' @name bg_cenpop2020
#' @docType data
#' @title bg_cenpop2020 (DATA) data.table with all US Census 2020 block groups
#' @description data.table with all US Census 2020 block groups, Census 2020 population count, 
#'   and lat/lon of Census2020-population-weighted centroid of block group
#' @details also see attributes(bg_cenpop2020) for source URL and date
#' @seealso   [blockgroupstats]
'bg_cenpop2020'
