# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_ejscreenit_50.R or similar files

#' @name testoutput_ejscreenit_50
#' @docType data
#' @title test data examples of output from [ejscreenit()] using testpoints_50, radius = 1
#' @details Just for convenience, installed with the package.
#'  A list of outputs, named 'table', 'map', and 'plot'
#' @seealso [testpoints_5] [testpoints_50] [testpoints_500]
#'
#'   [testoutput_ejscreenit_5] [testoutput_ejscreenit_50] [testoutput_ejscreenit_500]
'testoutput_ejscreenit_50'
