# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testpoints_overlap3.R or similar files

#' @name testpoints_overlap3
#' @docType data
#' @title test points data.frame with columns note, lat, lon
#' @details examples of test points for testing functions that need lat lon,
#'   with 3 overlapping 1-mile radius circles. To view these points:
#'  ```
#'   pts <- testpoints_overlap3
#'
#'   mapfast(pts, radius = 1)  
#'     
#'   plotblocksnearby(pts, radius = 1)
#'  ```
'testpoints_overlap3'
