# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testshapes_2.R or similar files

#' @name testshapes_2
#' @docType data
#' @title testshapes_2 dataset
#' @description Sample shapefile/polygon data as spatial data.frame
'testshapes_2'
