# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_metadata4pins.R or similar files

#' @name metadata4pins
#' @docType data
#' @title metadata about data object, for pins
#' @details metadata such as description of dataset, for pins board data in EJAM package
'metadata4pins'
