 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testpoints_50.R or similar files

#' @name testpoints_50
#' @docType data
#' @title test points data.frame with columns sitenumber, lat, lon
#' @description Examples of what could be inputs to functions that need points specified by lat lon
#' @details Just for convenience, these are installed with the package, and are
#'  the equivalent of results of reading the .xlsx test data files.
#' @seealso [testpoints_5] [testpoints_50] [testpoints_500]
#'   
#'   [testoutput_ejscreenit_5] [testoutput_ejscreenit_50] [testoutput_ejscreenit_500]
'testpoints_50'
