# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_ejscreenapi_plus_5.R or similar files

#' @name testoutput_ejscreenapi_plus_5
#' @docType data
#' @title test data examples of output from [ejscreenapi_plus()] using testpoints_5, radius = 1
#' @details Just for convenience, installed with the package.
 #'  Has header row, plus a row for each point, and about 300+ columns of buffer summary results.
#' @seealso [testpoints_5] [testpoints_50] [testpoints_500]
#'
#'   [testoutput_ejscreenit_5] [testoutput_ejscreenit_50] [testoutput_ejscreenit_500]
'testoutput_ejscreenapi_plus_5'
