# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_names_e_avg.R or similar files

#' @name names_e_avg
#' @docType data
#' @title a list of variable names for internal use in EJAM
#' @details To see other groups of variables: unique(map_headernames$varlist)
#' @keywords internal
#' @seealso  [varinfo()]  [map_headernames]  [names_d] [names_e]
'names_e_avg'
