# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_high_pctiles_tied_with_min.R or similar files

#' @name high_pctiles_tied_with_min
#' @docType data
#' @title high_pctiles_tied_with_min (DATA) internal data used to handle cases where multiple places are tied for the lowest indicator score
'high_pctiles_tied_with_min'
