# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_meters_per_mile.R or similar files

#' @name meters_per_mile
#' @docType data
#' @title how many meters are in one mile (for conversions between units)
#' @description 1609.344 meters per mile
'meters_per_mile'
