# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_naicstable.R or similar files

#' @name naicstable
#' @docType data
#' @title naicstable (DATA) data.table of NAICS code(s) and industry names for each EPA-regulated site
#' @description data.table of NAICS code(s) and industry names for each EPA-regulated site in Facility Registry Service
#' Also has the 2,3,4,5,and 6-digit NAICS that this code falls under, where relevant for given length
#' @details This is similar to the data file EJAM::NAICS but in a more useful format and newer functions work with it.
#' see [NAICS.com](https://naics.com)
#' @seealso [EJAM::naics_from_any()] [EJAM::NAICS]  [EJAM::naics_categories()]  [EJAM::naics_findwebscrape()]
'naicstable'
