# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_getblocksnearby_1000pts_1miles.R or similar files

#' @name testoutput_getblocksnearby_1000pts_1miles
#' @docType data
#' @title test output of getblocksnearby(), and is an input to doaggregate()
#' @details This is the output of getblocksnearby(testpoints_1000, radius = 1)
#' @seealso [getblocksnearby()]  [doaggregate()]  [testpoints_1000]
'testoutput_getblocksnearby_1000pts_1miles'
