# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_ejscreenRESTbroker2table_na_filler.R or similar files

#' @name ejscreenRESTbroker2table_na_filler
#' @docType data
#' @title used to fill in NA values in correctly-formatted output of [ejscreenRESTbroker2table()] when no data are available
'ejscreenRESTbroker2table_na_filler'
