# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_doaggregate_1000pts_1miles.R or similar files

#' @name testoutput_doaggregate_1000pts_1miles
#' @docType data
#' @title test output of doaggregate()
#' @details This is the output of doaggregate(testoutput_getblocksnearby_1000pts_1miles, sites2states_or_latlon = testpoints_1000, radius = 1, include_ejindexes = TRUE)
#' @seealso [doaggregate()] [ejamit()] [testoutput_getblocksnearby_1000pts_1miles] [testpoints_1000]
'testoutput_doaggregate_1000pts_1miles'
