# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_islandareas.R or similar files

#' @name islandareas
#' @docType data
#' @title islandareas (DATA) table, bounds info on lat lon of US Island Areas
#' @description data.frame of info on approximate lat lon bounding boxes around
#'   American Samoa, Guam, the 
#'   Commonwealth of the Northern Mariana Islands (Northern Mariana Islands),
#'   and the United States Virgin Islands.
#'   
#'   See also [stateinfo] and [stateinfo2]
#'   
#'   See [Census documentation](http://www.census.gov/geo/reference/gtc/gtc_island.html)
#'   
#'   See source package files datacreate_islandareas.R or EJAM/data-raw/islandareas.xlsx
#'   
#'   Note the US minor outlying islands are not in that list and are widely dispersed.
#'   They include Midway Islands, etc.
'islandareas'
