# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_SIC.R or similar files

#' @name SIC
#' @docType data
#' @title SIC (DATA) named list of all SIC code numbers and category name for each
#' @details Also see [SIC info](https://siccode.com)
#' @seealso [SIC] [sictable] [sic_categories()]
'SIC'
