# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_default_points_shown_at_startup.R or similar files

#' @name default_points_shown_at_startup
#' @docType data
#' @title Default Points Shown at Startup
#' keywords internal
'default_points_shown_at_startup'
