# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_ejampackages.R or similar files

#' @name ejampackages
#' @docType data
#' @title ejampackages (DATA) list of names of key EJAM-related R packages
#' @keywords internal
'ejampackages'
