# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_names_wts.R or similar files

#' @name names_wts
#' @docType data
#' @title a list of variable names for internal use in EJAM
'names_wts'
