# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_doaggregate_10pts_1miles.R or similar files

#' @name testoutput_doaggregate_10pts_1miles
#' @docType data
#' @title test output of doaggregate()
#' @details This is the output of doaggregate(testoutput_getblocksnearby_10pts_1miles, sites2states_or_latlon = testpoints_10, radius = 1, include_ejindexes = TRUE)
#' @seealso [doaggregate()] [ejamit()] [testoutput_getblocksnearby_10pts_1miles] [testpoints_10]
'testoutput_doaggregate_10pts_1miles'