# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_formulas_d.R or similar files

#' @name formulas_d
#' @docType data
#' @title formulas_d (DATA) table of formulas to aggregate or calculate indicators
#' @description These formulas can describe how each indicator is calculated from 
#'   other variables like counts or how it is aggregated as a weighted mean, etc.
#' @details Created for EJAM by datacreate_formulas.R script
#' 
#' Can be used by [calc_ejam()] for aggregation or to create a derived custom
#'   indicator for all US blockgroups based on counts obtained from the ACS.)
'formulas_d'
