# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_getblocksnearby_10pts_1miles.R or similar files

#' @name testoutput_getblocksnearby_10pts_1miles
#' @docType data
#' @title test output of getblocksnearby(), and is an input to doaggregate()
#' @details This is the output of getblocksnearby(testpoints_10, radius = 1)
#' @seealso [getblocksnearby()]  [doaggregate()]  [testpoints_10]
'testoutput_getblocksnearby_10pts_1miles'
