# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_censusplaces.R or similar files

#' @name censusplaces
#' @docType data
#' @title censusplaces (DATA) Census FIPS and other basic info on roughly 40,000 cities/towns/places
#' @description Table of US cities and other Census Designated Places, Incorporated Places, and County Subdivisions
#' @details from [https://www2.census.gov/geo/docs/reference/codes/PLACElist.txt](https://www2.census.gov/geo/docs/reference/codes/PLACElist.txt) 
#' Column names: eparegion, ST, stfips, countyname, countyfips, placename, fips
'censusplaces'
