# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testpoints_1000.R or similar files

#' @name testpoints_1000
#' @docType data
#' @title test points data.frame with columns sitenumber, lat, lon
'testpoints_1000'
